USE progetto;

DROP TRIGGER IF EXISTS CHECK_PIVA_CLIENTE;
DELIMITER //
CREATE TRIGGER CHECK_PIVA_CLIENTE BEFORE INSERT ON CLIENTE FOR EACH ROW
BEGIN
 IF (char_length (NEW.PIVA)) != 11 THEN SET NEW.PIVA = NULL;
 END IF;
END; //
DELIMITER; 

DROP TRIGGER IF EXISTS CHECK_PIVA_FORNITORE;
DELIMITER //
CREATE TRIGGER CHECK_PIVA_FORNITORE BEFORE INSERT ON FORNITORE FOR EACH ROW
BEGIN
 IF (char_length (NEW.PIVA ) ) != 11 THEN SET NEW.PIVA = NULL;
 END IF;
END; //
DELIMITER; 

DROP TRIGGER IF EXISTS CHECK_NUMERO_DI_TELEFONO_CLIENTE;
DELIMITER //
CREATE TRIGGER CHECK_NUMERO_DI_TELEFONO_CLIENTE BEFORE INSERT ON TELEFONOCLIENTE FOR EACH ROW
BEGIN
 IF (char_length (NEW.numerotelefono)) > 15 THEN SET NEW.numerotelefono = NULL;
 END IF;
END; //
DELIMITER; 

DROP TRIGGER IF EXISTS CHECK_NUMERO_DI_TELEFONO_FORNITORE;
DELIMITER //
CREATE TRIGGER CHECK_NUMERO_DI_TELEFONO_FORNITORE BEFORE INSERT ON TELEFONOFORNITORE FOR EACH ROW
BEGIN
 IF (char_length (NEW.numerotelefono) > 15) THEN SET NEW.numerotelefono = NULL;
 END IF;
END; //
DELIMITER; 

DROP TRIGGER IF EXISTS CHECK_PIVA_CLIENTE_1;
DELIMITER //
CREATE TRIGGER CHECK_PIVA_CLIENTE_1 BEFORE UPDATE  ON CLIENTE FOR EACH ROW
BEGIN
 IF (char_length (NEW.PIVA ) ) != 11 THEN SET NEW.PIVA = OLD.piva;
 END IF;
END; //
DELIMITER; 

DROP TRIGGER IF EXISTS CHECK_PIVA_FORNITORE_1;
DELIMITER //
CREATE TRIGGER CHECK_PIVA_FORNITORE_1 BEFORE UPDATE ON FORNITORE FOR EACH ROW
BEGIN
 IF (char_length (NEW.PIVA)) != 11 THEN set NEW.PIVA = OLD.PIVA;
 END IF;
END; //
DELIMITER; 

DROP TRIGGER IF EXISTS CHECK_NUMERO_DI_TELEFONO_CLIENTE_1;
DELIMITER //
CREATE TRIGGER CHECK_NUMERO_DI_TELEFONO_CLIENTE_1 BEFORE UPDATE ON TELEFONOCLIENTE FOR EACH ROW
BEGIN
 IF (char_length (NEW.numerotelefono)) > 15 THEN SET NEW.numerotelefono = OLD.numerotelefono;
 END IF;
END; //
DELIMITER; 

DROP TRIGGER IF EXISTS CHECK_NUMERO_DI_TELEFONO_FORNITORE_1;
DELIMITER //
CREATE TRIGGER CHECK_NUMERO_DI_TELEFONO_FORNITORE_1 BEFORE UPDATE ON TELEFONOFORNITORE FOR EACH ROW
BEGIN
 IF (char_length (NEW.numerotelefono) > 15) THEN SET NEW.numerotelefono = OLD.numerotelefono;
 END IF;
END; //
DELIMITER; 

DROP TRIGGER IF EXISTS CHECK_DISPONIBILE; 
DELIMITER // 
CREATE TRIGGER CHECK_DISPONIBILE BEFORE INSERT ON StampanteDigitale FOR EACH ROW
BEGIN 
IF( New.NUMEROPEZZI <= 0) THEN 
							SET NEW.Disponibile = FALSE; 
END IF; 
END; //
DELIMITER; 

DROP TRIGGER IF EXISTS CHECK_DISPONIBILE_1; 
DELIMITER // 
CREATE TRIGGER CHECK_DISPONIBILE_1 BEFORE UPDATE ON StampanteDigitale FOR EACH ROW
BEGIN 
IF(new.NUMEROPEZZI <= 0) THEN
						   SET NEW.Disponibile = FALSE;
END IF; 
END; //
DELIMITER; 

DROP TRIGGER IF EXISTS CHECK_DISPONIBILE_2; 
DELIMITER // 
CREATE TRIGGER CHECK_DISPONIBILE_2 BEFORE INSERT ON StampanteDigitale FOR EACH ROW
BEGIN 
IF(new.NUMEROPEZZI > 0) THEN  
						   SET NEW.Disponibile = TRUE;
END IF; 
END; //
DELIMITER; 

DROP TRIGGER IF EXISTS CHECK_DISPONIBILE_3; 
DELIMITER // 
CREATE TRIGGER CHECK_DISPONIBILE_3 BEFORE UPDATE ON StampanteDigitale FOR EACH ROW
BEGIN 
IF(new.NUMEROPEZZI > 0) THEN  
						   SET NEW.Disponibile = TRUE;
END IF; 
END; //
DELIMITER; 

DROP TRIGGER IF EXISTS CHECK_ANNO_DI_PRODUZIONE;
DELIMITER // 
CREATE TRIGGER CHECK_ANNO_DI_PRODUZIONE BEFORE INSERT ON StampanteDigitale FOR EACH ROW
BEGIN 
IF(NEW.AnnoDiProduzione > YEAR(NOW()))
THEN SET NEW.AnnoDiProduzione = YEAR(NOW());
END IF; 
END; //
DELIMITER; 

DROP TRIGGER IF EXISTS CHECK_ANNO_DI_PRODUZIONE_1;
DELIMITER // 
CREATE TRIGGER CHECK_ANNO_DI_PRODUZIONE_1 BEFORE UPDATE ON StampanteDigitale FOR EACH ROW
BEGIN 
IF(NEW.AnnoDiProduzione > YEAR(NOW()))
THEN SET NEW.AnnoDiProduzione = OLD.AnnoDiProduzione;
END IF; 
END; //
DELIMITER; 

DROP TRIGGER IF EXISTS CHECK_ANNO_DI_PRODUZIONE_PRODOTTOCONTABILE;
DELIMITER // 
CREATE TRIGGER CHECK_ANNO_DI_PRODUZIONE_PRODOTTOCONTABILE BEFORE INSERT ON prodottocontabile FOR EACH ROW
BEGIN 
IF(NEW.AnnoDiProduzione > YEAR(NOW()))
THEN SET NEW.AnnoDiProduzione = YEAR(NOW());
END IF; 
END; //
DELIMITER; 

DROP TRIGGER IF EXISTS CHECK_ANNO_DI_PRODUZIONE_PRODOTTOCONTABILE_1;
DELIMITER // 
CREATE TRIGGER CHECK_ANNO_DI_PRODUZIONE_PRODOTTOCONTABILE_1 BEFORE UPDATE ON prodottocontabile FOR EACH ROW
BEGIN 
IF(NEW.AnnoDiProduzione > YEAR(NOW()) )
THEN SET NEW.AnnoDiProduzione = OLD.AnnoDiProduzione;
END IF; 
END; //
DELIMITER;

DROP TRIGGER IF EXISTS CHECK_DATA_PAGAMENTO;
DELIMITER // 
CREATE TRIGGER CHECK_DATA_PAGAMENTO BEFORE INSERT ON pagamento FOR EACH ROW
BEGIN 
IF(NEW.Data > NOW())
THEN SET NEW.Data = NOW();
END IF; 
END; //
DELIMITER; 

DROP TRIGGER IF EXISTS CHECK_DATA_PAGAMENTO_1;
DELIMITER // 
CREATE TRIGGER CHECK_DATA_PAGAMENTO_1 BEFORE UPDATE ON  pagamento FOR EACH ROW
BEGIN 
IF(NEW.Data > NOW())
THEN SET NEW.Data = OLD.Data;
END IF; 
END; //
DELIMITER;

DROP TRIGGER IF EXISTS GESTIONE_DATO_RIDONDANTE;
DELIMITER // 
CREATE TRIGGER GESTIONE_DATO_RIDONDANTE AFTER INSERT ON assistenza FOR EACH ROW
BEGIN 
UPDATE cliente 
SET NumeroAssistenzeRichieste = NumeroAssistenzeRichieste + 1
WHERE piva = NEW.idCliente; 
END; //
DELIMITER;

DROP TRIGGER IF EXISTS GESTIONE_DATO_RIDONDANTE_1;
DELIMITER // 
CREATE TRIGGER GESTIONE_DATO_RIDONDANTE_1 BEFORE UPDATE ON assistenza FOR EACH ROW
BEGIN 
IF (NEW.idCliente <> OLD.idCliente)
THEN
UPDATE cliente 
SET NumeroAssistenzeRichieste = NumeroAssistenzeRichieste - 1
WHERE piva = OLD.idCliente; 
END IF; 
END; //
DELIMITER;

DROP TRIGGER IF EXISTS GESTIONE_MARCA_PRODOTTOCONTABILE ;
DELIMITER // 
CREATE TRIGGER GESTIONE_MARCA_PRODOTTOCONTABILE BEFORE INSERT ON prodottocontabile FOR EACH ROW
BEGIN 
IF(NEW.aziendaproduttrice NOT IN ("RCH", "EMOTIQ" , "Olivetti"))
THEN SET NEW.aziendaproduttrice = NULL; 
END IF; 
END; //
DELIMITER;

DROP TRIGGER IF EXISTS GESTIONE_MARCA_PRODOTTOCONTABILE_1 ;
DELIMITER // 
CREATE TRIGGER GESTIONE_MARCA_PRODOTTOCONTABILE_1 BEFORE UPDATE ON prodottocontabile FOR EACH ROW
BEGIN 
IF(NEW.aziendaproduttrice NOT IN ("RCH", "EMOTIQ" , "Olivetti"))
THEN SET NEW.aziendaproduttrice = OLD.aziendaproduttrice ; 
END IF; 
END; //
DELIMITER;

DROP TRIGGER IF EXISTS GESTIONE_MARCA_STAMPANTEDIGITALE ;
DELIMITER // 
CREATE TRIGGER GESTIONE_MARCA_STAMPANTEDIGITALE BEFORE INSERT ON stampantedigitale FOR EACH ROW
BEGIN 
IF(NEW.aziendaproduttrice NOT IN ("Konica Minolta", "Canon", "Develop"))
THEN SET NEW.aziendaproduttrice = NULL; 
END IF; 
END; //
DELIMITER;

DROP TRIGGER IF EXISTS GESTIONE_MARCA_STAMPANTEDIGITALE_1 ;
DELIMITER // 
CREATE TRIGGER GESTIONE_MARCA_STAMPANTEDIGITALE_1 BEFORE UPDATE ON stampantedigitale FOR EACH ROW
BEGIN 
IF(NEW.aziendaproduttrice NOT IN ("Konica Minolta", "Canon", "Develop"))
THEN SET NEW.aziendaproduttrice = OLD.aziendaproduttrice ; 
END IF; 
END; //
DELIMITER ;